### ISSUE TITLE
First Meeting

### ISSUE THREAD

**Issue by frabbitry** [frabbitry/Ulysses#1]
Let's set up possible meeting times y'all. 

I'm free most of the day on Tuesdays and Thursdays, but I can find an hour or two to spare on Mondays, Wednesdays, or Fridays if that works better.

**Comment by BMT45** [comment]
I’m usually able to meet up on Tuesdays and Thursdays from 2-4 works for me.   Monday and Wednesday 2-3:45 works well for me as well

**Comment by KSD32** [comment]
I can meet on Tuesday and Thursday from 2:30 - 5.

**Comment by frabbitry** [comment]
Want to meet on Tuesdays at 2:30, then? And I guess that we could meet in the library?

**Comment by ebeshero** [comment]
@frabbitry @KSD32 @BMT45 There's also this "Center for the Digital Text" I keep hearing about...It's down in FOB 131...

**Comment by ebeshero** [comment]
@frabbitry Quick message here as you're trying to coordinate times...I sent you an e-mail to your Pitt address but not sure you'll see it there first. If you're around campus after 3:45, can you stop by my office quickly? 
@BMT45 I think I'll be meeting at 4 about honor society inductions, but feel free to stop by re your article just in case.

**Comment by frabbitry** [comment]
@ebeshero I just responded to your Pitt email. I usually see those before I see notifications from GitHub. 

Alternatively, we could meet on Tuesdays at 2:30 in the Center for the Digital Text. I don't think I've ever been in FOB 131, but I'm always down for adventures.
