### ISSUE TITLE
More Stuff To Do

### ISSUE THREAD

**Issue by frabbitry** [frabbitry/Ulysses#10]
Moving forward with the *Ulysses* project, we want to mark up three more sections, but this time we want to pick them from the Wanderings of Ulysses. Just pick a section from "The Wanderings" and comment it below so that we dont all end up doing the same section. In addition, be sure that the section you're marking up DOES NOT look like a play. We don't want to significantly alter the schema to include that section right now.

**Comment by frabbitry** [comment]
I'm going to claim the Lotus Eaters section

**Comment by KSD32** [comment]
I'll take Calypso
