### ISSUE TITLE
Coming Up with a Schema

### ISSUE THREAD

**Issue by frabbitry** [frabbitry/Ulysses#2]
Hey guys. I was thinking that we might want to start thinking of what our schema would look like. 

I was kind of bored this morning, so I went and uploaded a bunch of .txt files that contain the various sections/chapters of Ulysses. The outline of the entire book looks something like this: 

- The Telemachiad 
     - Telemachus
     - Nestor 
     - Proteus
- The Wanderings of Ulysses
    - Calypso
    - Lotus-Eaters
    - Hades
    - Aeolus 
    - Lestrygonians
    - Scylla and Charybdis
    - The Wandering Rocks
    - Sirens
    - Cyclops 
    - Nausicaa 
    - Oxen of the Sun
    - Circe
- The Homecoming
    - Eumaeus 
    - Ithaca
    - Penelope 

If you're at all familar with *The Odyssey* by Homer, you'll notice that the outline of *Ulysses* basically follows the outline of *The Odyssey*, which is kind of a cool reference in and of itself, but not something I think we'll be handling with markup. 

What I do want to handle with markup are the specific references listed in the book, whether those are literary allusions, religious imagery, or, probably most significant to this project, locations, especially locations in the city of Dublin. There are many annotations of *Ulysses*, or books listing the references. I have the Millstein Library's print copy of Gifford's annotation, but there are other annotations out there. (One online, partial adaptation of the Gifford annotation can be found [here](http://www.columbia.edu/~fms5/ulys.htm).) These annotations list locations, some even street addresses, of places relevant in various sections of *Ulysses*. I would like to tag those locations with their respective latitude/longitude coordinates (how we link the addresses in the annotation/text to geodata we can put on a map is something still to be determined), tag other references or maybe even themes, and then put all of that on a map. I'm hoping that this will then display Joyce's recreated Dublin in a way, so that we can see not only the locations he uses but also what those locations mean and what context they have in *Ulysses*. 

So... what should our schema look like? I actually tagged a page of Ulysses (p. 71) for my XML 3 assignment, and I put that xml file in /XML/Examples to maybe give you guys an idea of what this markup might look like. (While I tagged locations and references on that page, I also was messing around with some rudimentary sentiment analysis, which should be ignored because I think that's outside the scope of this project. Just pretend that the "emotion" tags aren't there at all.) If you guys wanted to take a look maybe at the online annotation and the various .txt files I've uploaded, I would be open to any suggestions as to what the schema should look like. 

I also know that *Ulysses* is huge and that we should probably only work with one section of it. Which section should that be? I'm kind of inclined to work with "The Wanderings of Ulysses" just because it has a lot of location references in it, but I also know that that's the longest of the three sections and will probably take forever to mark up. 

Sorry for the super long post, I just wanted to get started on thinking about these things before our first meeting so that we can hit the ground running, in a sense. Let me know what you guys think!

**Comment by ebeshero** [comment]
@frabbitry That outer "superstructure" looks fairly standard for outer sections of something divided into sections or books, subdivided into chapters...is that what they're called in editions of *Ulysses*?  

What I'm curious about is what happens with what we'd want to call "paragraphs" inside those chapters. There are a lot of white space divisions in passages like this:

```
Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed. A yellow dressinggown, ungirdled, was sustained gently behind him on the mild morning air. He held the bowl aloft and intoned:

—Introibo ad altare Dei.

Halted, he peered down the dark winding stairs and called out coarsely:

—Come up, Kinch! Come up, you fearful jesuit!

```
But the key thing here is that those long em dashes `—` are signalling spoken passages. You could borrow from the TEI here to use their `<said>` element for these. Take a look at the TEI element spec for `<said>`: <http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-said.html>

TEI is the language of the [Text Encoding Initiative](http://www.tei-c.org/), a consortium of people around the world who help maintain a standard XML tagset for literary/cultural documents. I'm active with them (I'm on the TEI Technical Council and work with 10 other people on maintaining their codebase/schema), so I'll occasionally suggest something TEI for student project teams b/c it's on my mind. :)  Anyway, the TEI has lots of options for tagging spoken or thought passages that are well worth reading about to give you some ideas. 

But having tormented @KSD32 with TEI last fall, I actually, seriously think your group might want liberate yourselves from it, just as you're getting started now, and write and refine your own schema with your own sense of structure for this spring. You should be able to *convert* your markup to TEI later--we can talk more about that if you like. But you can always do up your own Relax NG schema model, read about TEI elements, get ideas/snag what you want from the TEI tagset, and write what we call "TEI-inflected" code. 

As you're working up your schema, it'll help to think of your structural markup as giving you *frameworks* or *containers* for the data you want to track inside (locations, references, allusions, etc) inside. So a paragraph or maybe even a sentence could be the smallest piece of structural hierarchy in which you can pinpoint a place name--you'll find a reference to Paris in sentence 3, paragraph 5, chapter 7, section 2... That level of structural precision is a cool thing about what you can model in XML!

**Comment by frabbitry** [comment]
@ebeshero I like the idea of using something like a "said" element for the free indirect discourse, signaled by dashes and outside of paragraphs. You could then put the "said" element both on the same level as a paragraph element and inside of the paragraph element for cases in which characters are saying things inside of paragraphs (off the top of my head I'm thinking of the last couple of pages of the "Penelope" section). 

For most of the book, using a fairly straightforward hierarchy of sections divided into chapters (I'm not really sure what they're referred to as in editions of Ulysses) divided into things like paragraphs, etc. makes a lot of sense. However, there are parts of the book that don't follow that structure. The "Circe" section is written like a play. How would we deal with that? Would you want to create a separate schema just for those 200 pages? Or just incorporate a schema for that section into the larger Ulysses section (I'm guessing that you would have to use a lot of asterisks)?

Speaking of TEI, I did a quick search for "Ulysses XML TEI" just for fun and found that other people are tagging Ulysses (and other Joyce works) using TEI XML, which I think is really cool. One such project was even on GitHub (an open edition project?), so I went and snooped on their schema code only to find that it was huge and mostly incomprehensible to me, with my limited knowledge of how schemas work. Still, maybe at least borrowing from TEI wouldn't be such a bad idea. From my brief glance at it, it didn't look like that project was tagging locations like we would, but maybe TEI could be useful for creating the frameworks and structures in which we can tag locations and other references.

**Comment by ebeshero** [comment]
@frabbitry Yep--Ulysses has attracted a lot of digital project work over the years!  The GitHub repo is this one, right? https://github.com/open-editions/corpus-joyce-ulysses-tei 
From the look of their markup, they're using `<lb/>` elements, which tells me they're representing pages literally--and I'm not sure if it's trained on print editions or ms, though it doesn't look bumpy enough for ms markup. But *this* project on Ulysses and Finnegan's Wake is ALL about the manuscripts: http://www.jjda.ie/main/JJDA/U/UHome.htm# 

The TEI work ongoing on Joyce now might be kind of akin to building digital cathedrals, and is well worth admiring. But students and everyone, happily, can now build a data-rich project of a different order now that *Ulysses* is free from copyright (There has been *quite* a lot of buzz about that since about 2012; see https://www.pbs.org/newshour/arts/portraits-of-james-joyce ).
